-- WoW client Lua is 5.1-based.
std = "lua51"
max_line_length = false

-- 212/self, 432/self: WoW's `frame:SetScript("OnClick", function(self) ... end)`
-- idiom means "self" goes unused or gets shadowed constantly and isn't a bug.
-- 611/612: whitespace-only warnings, purely cosmetic, no behavioral signal.
ignore = { "212/self", "432/self", "611", "612" }

-- SavedVariables (declared in the .toc) and other addon-wide globals this
-- codebase assigns to directly (see Core.lua, CoordsData.lua).
globals = {
    "PSM",
    "PetStableManagementDB",
    "PSM_UserNotes",
    "CoordsData",
    "AbilitiesData",
    "ModelsData",
    "SLASH_PETSTABLE1",
    "SLASH_PETSTABLE2",
    "SLASH_PETSWAP1",
}

-- WoW API globals this addon reads but never assigns. Generated by running
-- luacheck with no globals config and collecting every "accessing undefined
-- variable" warning (see AGENT_INSTRUCTIONS.md / CLAUDE.md for the command) --
-- add to this list, don't disable W113, when a new Blizzard API is used.
read_globals = {
    "CHECKBOX_INDENT_X",
    "C_AddOns",
    "C_Map",
    "C_PetJournal",
    "C_QuestLog",
    "C_SpecializationInfo",
    "C_Spell",
    "C_StableInfo",
    "C_SuperTrack",
    "C_Timer",
    "CreateFrame",
    "EasyMenu",
    "ElvUI",
    "Enum",
    "GameFontHighlightSmall",
    "GameTooltip",
    "GetCursorPosition",
    "GetMinimapShape",
    "GetMouseFoci",
    "GetMouseFocus",
    "GetRealZoneText",
    "GetRealmName",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpellInfo",
    "GetTime",
    "InterfaceOptionsFrame",
    "InterfaceOptionsFrame_OpenToCategory",
    "InterfaceOptions_AddCategory",
    "InCombatLockdown",
    "IsControlKeyDown",
    "IsMouseButtonDown",
    "IsPlayerSpell",
    "IsShiftKeyDown",
    "LibStub",
    "Minimap",
    "OpenWorldMap",
    "PlayerHasToy",
    "SetPortraitTextureFromCreatureDisplayID",
    "Settings",
    "SettingsPanel",
    "SlashCmdList",
    "StableFrame",
    "ToggleDropDownMenu",
    "TooltipDataProcessor",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_SetText",
    "UIDropDownMenu_SetWidth",
    "UIParent",
    "UISpecialFrames",
    "UiMapPoint",
    "UnitAffectingCombat",
    "UnitClass",
    "UnitLevel",
    "UnitName",
    "UnitRace",
    "date",
    "debugprofilestop",
    "hooksecurefunc",
    "strsplit",
    "strtrim",
    "time",
}
